const crk = {
  curso: {
    nombre: "CRK Rob\u00f3tica 1",
    descripcion:
      "Curso de Crea Rob\u00f3tica con Krismar, nivel 1: Introducci\u00f3n a la Rob\u00f3tica, mec\u00e1nica y electr\u00f3nica",
    grados: [
      {
        id: 665,
        n: "Grado 1",
        position: 1,
        tipo: "grado",
        materias: [
          {
            id: 12469,
            n: "Rob\u00f3tica",
            position: 1,
            tipo: "materia",
            bloques: [
              {
                id: 33715,
                n: "Introducci\u00f3n",
                position: 1,
                tipo: "bloque",
                lecciones: [
                  {
                    id: 95441,
                    n: "\u00bfQu\u00e9 es la rob\u00f3tica?",
                    position: 1,
                    tipo: "leccion",
                    apps: [
                      {
                        i: "8914",
                        n: "Manual. Introducci\u00f3n a la rob\u00f3tica",
                        p: "crk_rob_1100",
                        c: "lectura",
                        pc: "-rob\u00f3tica-manual-contenido-Isaac Asimov-m\u00e1quina-robot-hermanos Capek-robota-trabajo-forzado",
                        o: "- Conoce el contenido del bloque de rob\u00f3tica.",
                      },
                      {
                        i: "9071",
                        n: "Las piezas en tu kit",
                        p: "crk_rob_1100a",
                        c: "lectura",
                        pc: "-rob\u00f3tica-kit-piezas-barra-flexible-engrane-uni\u00f3n-tope-flecha-hept\u00e1gono-polea-palito-popote-el\u00e1stico-cuerda-canica-bal\u00edn-LED-rojo-verde-RGB-camale\u00f3n-bot\u00f3n-zumbador-resistencia-eliminador-bater\u00eda-Ohms-interruptor-pontenci\u00f3metro-cable-fotorresistencia",
                        o: "-\tConoce las piezas que contiene tu kit de CRK.",
                      },
                      {
                        i: "8909",
                        n: "1. \u00bfQui\u00e9n es Aztek?",
                        p: "crk_rob_1101",
                        c: "lectura",
                        pc: "-rob\u00f3tica-Aztek-protagonista-tecnolog\u00eda-robot-expresivo-curioso-inteligente-creativo-travieso-aut\u00e9ntico-sincero-experimentar-hacer",
                        o: "- Conoce a Aztek.",
                      },
                      {
                        i: "7643",
                        n: "2. Historia de la rob\u00f3tica",
                        p: "crk_rob_1101a",
                        c: "video",
                        pc: "-rob\u00f3tica-historia-introducci\u00f3n-checo-robot-Issac-Asimov-m\u00e1quina-m\u00e1quina simple-rob\u00f3tica-Aztek-capek-dise\u00f1ar-construir-programar-taladro-tareas-est\u00edmulos ",
                        o: "- Conoce la historia y origen de la rob\u00f3tica.\n- Diferencia una m\u00e1quina de un robot.",
                      },
                      {
                        i: "8906",
                        n: "3. Los robots y su historia",
                        p: "crk_rob_1101b",
                        c: "aplicacion",
                        pc: "-rob\u00f3tica-origen-historia-hermanos Carpek-robota-checo-trabajo-duro-forzado-siglo XX-obra-teatro-tareas-humano-entorno-sensibles-aut\u00f3nomo-independiente-reprogramar-precisa",
                        o: "-\tConocer la historia y origen de la rob\u00f3tica.\n-\tDiferenciar una m\u00e1quina de un robot.\n",
                      },
                      {
                        i: "7723",
                        n: "4. Partes de un robot",
                        p: "crk_rob_1102a",
                        c: "video",
                        pc: "-rob\u00f3tica-partes-controlador-mec\u00e1nica-sensores-Aztek-instrucciones-programaci\u00f3n-energ\u00eda el\u00e9ctrica-aire-agua-sentidos-tacto-vista-gusto-olfato-o\u00eddo-cerebro-robot-informaci\u00f3n",
                        o: "-\tConoce las principales partes de un robot.\n-\tClasifica las partes de un robot.\n",
                      },
                      {
                        i: "8907",
                        n: "5. Partes de un robot",
                        p: "crk_rob_1102b",
                        c: "aplicacion",
                        pc: "-rob\u00f3tica-robot-pl\u00e1stico-energ\u00eda-electricidad-aire-agua-sensores-sentidos-metal-llantas-brazos-piernas-cerebro-manos-instrucciones-controlador-programaci\u00f3n-partes-mec\u00e1nicas",
                        o: "- Reconoce las partes que componen a un robot.\n- Enlista las partes que componen a un robot.\n",
                      },
                      {
                        i: "7724",
                        n: "6. Clasificaci\u00f3n de los robots",
                        p: "crk_rob_1103a",
                        c: "video",
                        pc: "-rob\u00f3tica-clasificaci\u00f3n-robots-poli articulados-m\u00f3viles-androides-h\u00edbridos-zoom\u00f3rficos-generaci\u00f3n-arquitectura-inteligencia-programaci\u00f3n-control",
                        o: "-\tCompara los diferentes tipos de robots que existen.\n-\tEnlista las caracter\u00edsticas principales de los diferentes tipos de robots.\n",
                      },
                      {
                        i: "8908",
                        n: "7. Clasifica a los robots",
                        p: "crk_rob_1103b",
                        c: "aplicacion",
                        pc: "-rob\u00f3tica-robot-pl\u00e1stico-energ\u00eda-articulados-m\u00f3viles-androides-zoom\u00f3rficos-h\u00edbridos\n",
                        o: "- Clasifica los robots en articulados, m\u00f3viles, androides, zoom\u00f3rficos, h\u00edbridos.\n\n",
                      },
                      {
                        i: "7730",
                        n: "8. Leyes de la rob\u00f3tica",
                        p: "crk_rob_1105a",
                        c: "video",
                        pc: "-rob\u00f3tica-Isaac-Asimov-leyes-robot-da\u00f1o-humano-da\u00f1o-seguir-proteger-inacci\u00f3n-\u00f3rdenes-conflicto-existencia-protecci\u00f3n-primera-segunda-tercera ley",
                        o: "-\tConoce qui\u00e9n fue Issac Asimov.\n-\tConoce las tres leyes de la rob\u00f3tica.\n-\tMenciona la raz\u00f3n principal por la que fueron elaboradas las tres leyes de la rob\u00f3tica.\n",
                      },
                      {
                        i: "7729",
                        n: "9. Ventajas y desventajas de los robots",
                        p: "crk_rob_1104a",
                        c: "video",
                        pc: "-rob\u00f3tica-ventajas-desventajas-usos-vida-repetitivas-aburridas-tareas-producci\u00f3n-costo-r\u00e1pidos-fuertes-precisos-calidad-riesgo-ser humano-actividades-tareas ",
                        o: "-\tMenciona algunas ventajas y desventajas que tienen los robots.\n-\tConoce algunas funciones que tienen los robots en nuestra sociedad.\n",
                      },
                      {
                        i: "8641",
                        n: "10. \u00bfQu\u00e9 tanto sabes de la rob\u00f3tica?",
                        p: "crk_rob_1106a",
                        c: "evaluacionC",
                        pc: "-evaluaci\u00f3n-rob\u00f3tica-introducci\u00f3n-Asimov-clasificaci\u00f3n-controlador-sensores-robot-ley-robot-zoom\u00f3rficos-androides-m\u00f3viles-poliarticulados-h\u00edbridos-brazo rob\u00f3tico\u2013checo-trabajo-m\u00e1quinas-almacenar-controlador-instrucciones-girar-sensores-recopilar-informaci\u00f3n-industria--realidad virtual-da\u00f1o-ser humano-obedecer-primera-segunda-tercera-partes mec\u00e1nicas",
                        o: "Menciona las diferencias entre un robot y una m\u00e1quina.\n- Enlista las partes de un robot y su funci\u00f3n.\n- Menciona las leyes de la rob\u00f3tica.\n- Explica las leyes de la rob\u00f3tica.\n- Reconoce los distintos tipos de robots.\n",
                      },
                    ],
                  },
                ],
              },
              {
                id: 33716,
                n: "Mec\u00e1nica",
                position: 2,
                tipo: "bloque",
                lecciones: [
                  {
                    id: 95442,
                    n: "Introducci\u00f3n",
                    position: 1,
                    tipo: "leccion",
                    apps: [
                      {
                        i: "8931",
                        n: "Manual. Introducci\u00f3n a la mec\u00e1nica",
                        p: "crk_mec_1200",
                        c: "lectura",
                        pc: "-rob\u00f3tica-robot-m\u00e1quina simples-simples-m\u00e1quina-plano inclinado-eje y rueda-palanca-eje-rueda-polea-cu\u00f1a-tornillo-engranes-carga-esfuerzo-fuerza-canicas-reflexi\u00f3n-desplazamiento-rueda de la fortuna-fortuna-palanca-esfuerzo-punto de apoyo-carga-sube y baja-carretilla-palanca-catapulta-poleas-fija-m\u00f3vil-compuesta-cu\u00f1a-cambio-direcci\u00f3n-tornillo-cilindro-engranes-pi\u00f1\u00f3n-corona-tren",
                        o: "-\tConoce el contenido del bloque de mec\u00e1nica de CRK.\n\n",
                      },
                      {
                        i: "8007",
                        n: "1. Introducci\u00f3n a la mec\u00e1nica",
                        p: "crk_mec_1201a",
                        c: "video",
                        pc: "-rob\u00f3tica-mec\u00e1nica-m\u00e1quina-simple-ingenier\u00eda-f\u00edsica-electr\u00f3nica-programaci\u00f3n-modelos-equipos-productos-crear-dise\u00f1ar-robot",
                        o: "-\tConoce qu\u00e9 es la mec\u00e1nica.",
                      },
                      {
                        i: "8018",
                        n: "2. Introducci\u00f3n a las m\u00e1quinas simples",
                        p: "crk_mec_1201b",
                        c: "video",
                        pc: "-rob\u00f3tica-mec\u00e1nica-m\u00e1quina-simple-f\u00edsica-plano-inclinado-eje-rueda-cu\u00f1a-polea-tornillo-palanca-mecanismo-mecanismo-transforma-energ\u00eda-vapor-carb\u00f3n-electricidad-petr\u00f3leo-renovables-sol-aire-movimiento",
                        o: "-\tMenciona qu\u00e9 hace una m\u00e1quina simple.\n-\tEnlista las m\u00e1quinas simples.\n",
                      },
                    ],
                  },
                  {
                    id: 95443,
                    n: "Plano inclinado",
                    position: 2,
                    tipo: "leccion",
                    apps: [
                      {
                        i: "8019",
                        n: "1. Plano inclinado",
                        p: "crk_mec_1202a",
                        c: "video",
                        pc: "-rob\u00f3tica-mec\u00e1nica-m\u00e1quina-simple-plano-inclinado-\u00e1ngulo-distancia-esfuerzo-bicicleta-canica-tobog\u00e1n-rampa-empujar-arrastrar",
                        o: "-\tDescribe un plano inclinado.\n-\tMenciona las ventajas de un plano inclinado.\n-\tDa ejemplos de las aplicaciones del plano inclinado.\n",
                      },
                      {
                        i: "8864",
                        n: "2. Sugerencias para armar tus modelos",
                        p: "crk_mec_1210a",
                        c: "simuladorcrk",
                        pc: "-polea",
                        o: "-Conoce la forma correcta para unir dos piezas en el armado de tus modelos.- Evita forzar las piezas para desarmar los modelos.- Conoce la forma de facilitar el paso de los popotes por los orificios de las piezas.- Conoce la forma correcta de armar una polea o un engrane.\n",
                      },
                      {
                        i: "8017",
                        n: "3. Ensamblando un plano inclinado",
                        p: "crk_mec_1202b",
                        c: "simuladorcrk",
                        pc: "-rob\u00f3tica-m\u00e1quinas simples-plano inclinado-inclinado-canica-popote-piezas-armado-ensamble",
                        o: "-\tIdentifica las piezas para construir tu m\u00e1quina simple.\n-\tConstruye tu plano inclinado.\n",
                      },
                      {
                        i: "8016",
                        n: "4. As\u00ed funciona el plano inclinado",
                        p: "crk_mec_1202c",
                        c: "simuladorcrk",
                        pc: "-rob\u00f3tica-mec\u00e1nica-maquina-simple-plano-inclinado-canica-popote-piezas-simulador-pelota-goma-bal\u00edn",
                        o: "- Compara la ca\u00edda de una pelota, canica o bal\u00edn en el plano inclinado.\n-\tExplica las diferencias en la ca\u00edda en el plano inclinado de cada uno de los objetos.\n",
                      },
                    ],
                  },
                  {
                    id: 95444,
                    n: "Eje y rueda",
                    position: 3,
                    tipo: "leccion",
                    apps: [
                      {
                        i: "8020",
                        n: "1. El eje y la rueda",
                        p: "crk_mec_1203a",
                        c: "video",
                        pc: "-rob\u00f3tica-mec\u00e1nica-m\u00e1quina-simple-rueda-eje-ventilador-desarmador-chapa-fortuna-circular-cil\u00edndrico",
                        o: "-\tExplica en qu\u00e9 consiste un eje y una rueda.\n-\tNombra algunas aplicaciones de esta m\u00e1quina simple\n",
                      },
                      {
                        i: "8015",
                        n: "2. Ensamblando una rueda de la fortuna",
                        p: "crk_mec_1203b",
                        c: "simuladorcrk",
                        pc: "-rob\u00f3tica-mec\u00e1nica-m\u00e1quina-simple-rueda-eje-ventilador-desarmador-chapa-fortuna-circular-cil\u00edndrico",
                        o: "-\tIdentifica las piezas para construir tu rueda de la fortuna.\n-\tConstruye tu modelo con un eje y una rueda.\n",
                      },
                      {
                        i: "8014",
                        n: "3. As\u00ed funciona la rueda de la fortuna",
                        p: "crk_mec_1203c",
                        c: "simuladorcrk",
                        pc: "-rob\u00f3tica-mec\u00e1nica-m\u00e1quina-simple-rueda-eje-ventilador-desarmador-chapa-fortuna-circular-cil\u00edndrico",
                        o: "-\tDescribe el comportamiento de la rueda de la fortuna al cambiar la velocidad y el sentido de su giro.\n-\tExplica c\u00f3mo intervienen el eje y la rueda en las diferentes velocidades del modelo.\n-\tDescribe c\u00f3mo intervienen el eje y la rueda en el cambio de giro del modelo construido.\n",
                      },
                    ],
                  },
                  {
                    id: 95445,
                    n: "Palanca",
                    position: 4,
                    tipo: "leccion",
                    apps: [
                      {
                        i: "8021",
                        n: "1. La palanca",
                        p: "crk_mec_1204a",
                        c: "video",
                        pc: "-rob\u00f3tica-mec\u00e1nica-m\u00e1quina-simple-palanca-catapulta-fulcro-brazo-esfuerzo-fuerza-punto-apoyo-barra-carga-carretilla-pala",
                        o: "-\tExplica en qu\u00e9 consiste la palanca como m\u00e1quina simple.\n-\tConoce las partes de una palanca.\n-\tConoce los tipos de palanca.\n",
                      },
                      {
                        i: "8013",
                        n: "2. Ensamblando una catapulta",
                        p: "crk_mec_1204b",
                        c: "simuladorcrk",
                        pc: "-rob\u00f3tica-mec\u00e1nica-m\u00e1quina-simple-catapulta-palanca",
                        o: "-\tIdentifica las piezas para construir tu catapulta.\n-\tConstruye tu catapulta.\n-\tReconoce en el modelo a la palanca como m\u00e1quina simple.\n",
                      },
                      {
                        i: "8012",
                        n: "3. As\u00ed funciona la catapulta",
                        p: "crk_mec_1204c",
                        c: "simuladorcrk",
                        pc: "-rob\u00f3tica-mec\u00e1nica-m\u00e1quina-simple-catapulta-liga-palanca-cubo",
                        o: "-\tConoce el funcionamiento de una catapulta.\n-\tReconoce en la catapulta a la palanca como m\u00e1quina simple.\n-\tExplica a qu\u00e9 se debe que el cubo alcance diferentes distancias al ser lanzado con la catapulta y utilizando diferentes \u00e1ngulos en su brazo.\n",
                      },
                    ],
                  },
                  {
                    id: 95446,
                    n: "Polea",
                    position: 5,
                    tipo: "leccion",
                    apps: [
                      {
                        i: "8022",
                        n: "1. La polea",
                        p: "crk_mec_1205a",
                        c: "video",
                        pc: "-rob\u00f3tica-mec\u00e1nica-m\u00e1quina-simple-polea-gr\u00faa-polipastos-pozo-fijas-m\u00f3viles-cuerda-liga-banda-eje-llanta-armadura-fuerza-esfuerzo-reducir",
                        o: "-\tDescribe en qu\u00e9 consiste una polea.\n-\tConoce las partes de una polea.\n-\tConoce los diferentes tipos de poleas que existen.\n",
                      },
                      {
                        i: "8011",
                        n: "2. Ensamblando un sistema de poleas",
                        p: "crk_mec_1205b",
                        c: "simuladorcrk",
                        pc: "-rob\u00f3tica-m\u00e1quinas simples-poleas-peso-balanza-masa-balines",
                        o: "-\tIdentifica las piezas para construir un sistema de poleas.\n-\tConstruye tu sistema de poleas.\n",
                      },
                      {
                        i: "8010",
                        n: "3. As\u00ed funciona el sistema de poleas",
                        p: "crk_mec_1205c",
                        c: "simuladorcrk",
                        pc: "-rob\u00f3tica-mec\u00e1nica-maquina-simple-balanza-poleas-balines-bal\u00edn-equilibrar-masa",
                        o: "-\tEquilibra la balanza que se forma con el sistema de 2 y 4 poleas, utilizando diferente n\u00famero de balines.\n-\tExplica la diferencia para equilibrar las balanzas de 2 y 4 poleas utilizando balines de una unidad de peso.\n",
                      },
                    ],
                  },
                  {
                    id: 95447,
                    n: "Cu\u00f1a",
                    position: 6,
                    tipo: "leccion",
                    apps: [
                      {
                        i: "8023",
                        n: "1. La cu\u00f1a",
                        p: "crk_mec_1206a",
                        c: "video",
                        pc: "-rob\u00f3tica-mec\u00e1nica-m\u00e1quina-simple-ingeniero-ingeniera-Aztek-autom\u00f3vil-doble-simple-rampa-plano-inclinado-hacha-tornillo-cierre-cuchillo-guillotina",
                        o: "-\tExplica c\u00f3mo funciona una cu\u00f1a.\n-\tMenciona algunas aplicaciones de la cu\u00f1a\n",
                      },
                      {
                        i: "8709",
                        n: "2. Ensamblando una guillotina",
                        p: "crk_mec_1206b",
                        c: "simuladorcrk",
                        pc: "-rob\u00f3tica-m\u00e1quinas simples-guillotina-cu\u00f1a-plano inclinado-uni\u00f3n-cortar-separar",
                        o: "-\tIdentifica las piezas para construir una guillotina.\n-\tConstruye tu guillotina.\n-\tReconoce el uso de la cu\u00f1a en una guillotina.\n\n",
                      },
                      {
                        i: "8710",
                        n: "3. As\u00ed funciona la guillotina",
                        p: "crk_mec_1206c",
                        c: "simuladorcrk",
                        pc: "-rob\u00f3tica-mec\u00e1nica-maquina-simple-guillotina-cu\u00f1a-altura-fuerza",
                        o: "-\tReconoce el funcionamiento de la cu\u00f1a en la guillotina.\n-\tIdentifica c\u00f3mo influye la altura de la cu\u00f1a en la guillotina.\n",
                      },
                    ],
                  },
                  {
                    id: 95448,
                    n: "Tornillo",
                    position: 7,
                    tipo: "leccion",
                    apps: [
                      {
                        i: "8586",
                        n: "1. El tornillo",
                        p: "crk_mec_1207a",
                        c: "video",
                        pc: "-rob\u00f3tica-mec\u00e1nica-m\u00e1quina-simple-egipcios-tornillo-cu\u00f1a-plano-inclinado-agua-cabeza-rosca-cuerda-cuello-elevador-broca-corte",
                        o: "-\tConoce c\u00f3mo funciona un tornillo.\n-\tIdentifica las partes del tornillo.\n-\tMenciona los usos del tornillo.\n",
                      },
                      {
                        i: "8719",
                        n: "2. Ensambla un elevador de canicas",
                        p: "crk_mec_1207b",
                        c: "simuladorcrk",
                        pc: "-rob\u00f3tica-m\u00e1quinas simples-tornillo-elevador-canicas",
                        o: "-\tIdentifica las piezas para construir un elevador de canicas.\n-\tConstruye tu elevador de canicas.\n",
                      },
                      {
                        i: "8774",
                        n: "3. As\u00ed funciona el elevador",
                        p: "crk_mec_1207c",
                        c: "simuladorcrk",
                        pc: "-rob\u00f3tica-mec\u00e1nica-maquina-simple-elevador-tornillo-esfuerzo-canicas",
                        o: "-\tReconoce el funcionamiento del tornillo en el elevador.\n-\tCompara el esfuerzo que se requiere para subir diferente n\u00famero de canicas.\n",
                      },
                    ],
                  },
                  {
                    id: 95449,
                    n: "Engranes",
                    position: 8,
                    tipo: "leccion",
                    apps: [
                      {
                        i: "8024",
                        n: "1. Los engranes",
                        p: "crk_mec_1208a",
                        c: "video",
                        pc: "-rob\u00f3tica-mec\u00e1nica-m\u00e1quina-simple-ingeniero-ingeniera-Aztek-engrane-dientes-rueda-eje-pi\u00f1\u00f3n-corona-tren-horizontal-vertical-movimiento",
                        o: "- Conoce las partes de un sistema de engranes.\t\n- Describe un sistema de engranes.\n-\tConoce la funci\u00f3n del engrane.\n\n",
                      },
                      {
                        i: "8718",
                        n: "2. Ensamblando un tren de engranes",
                        p: "crk_mec_1208b",
                        c: "simuladorcrk",
                        pc: "-rob\u00f3tica-m\u00e1quinas simples-engranes-dientes-pi\u00f1\u00f3n-corona-velocidad-sentido",
                        o: "-\tIdentifica las piezas para construir un tren de engranes.\n-\tConstruye un tren de engranes con 6 engranes.\n",
                      },
                      {
                        i: "8775",
                        n: "3. As\u00ed funciona el tren de engranes",
                        p: "crk_mec_1208c",
                        c: "simuladorcrk",
                        pc: "-rob\u00f3tica-mec\u00e1nica-maquina-simple-engranes-vueltas-dientes-flechas-efuerzo",
                        o: "-\tConoce el funcionamiento del tren de engranes.\n-\tIdentifica la relaci\u00f3n que existen en los giros y velocidad de todos los componentes del tren de engranes.\n",
                      },
                    ],
                  },
                  {
                    id: 96351,
                    n: "Evaluaci\u00f3n",
                    position: 9,
                    tipo: "leccion",
                    apps: [
                      {
                        i: "8647",
                        n: "\u00bfQu\u00e9 tanto sabes de m\u00e1quinas simples?",
                        p: "crk_mec_1209a",
                        c: "evaluacionC",
                        pc: "-evaluaci\u00f3n-rob\u00f3tica-m\u00e1quinas simples-fuerza-trabajo-movimiento-distancia-plano inclinado-palanca-eje y rueda-rueda-cu\u00f1a-tornillo-engrane-pi\u00f1\u00f3n-corona-cabeza-rosca-cuerpo-pendiente-fulcro-apoyo-sentido-levantar-cargar-separar-unir-tiempo-fricci\u00f3n-resbaladilla-volant\u00edn-bicicleta",
                        o: "- Menciona la funci\u00f3n principal de una m\u00e1quina simple.\n- Enlista las m\u00e1quinas simples que existen.\n- Explica la funci\u00f3n principal de cada m\u00e1quina simple.\n- Menciona ejemplos de uso de cada m\u00e1quina simple.\n",
                      },
                    ],
                  },
                ],
              },
              {
                id: 33717,
                n: "Electr\u00f3nica",
                position: 3,
                tipo: "bloque",
                lecciones: [
                  {
                    id: 95450,
                    n: "Introducci\u00f3n",
                    position: 1,
                    tipo: "leccion",
                    apps: [
                      {
                        i: "9072",
                        n: "Manual. Introducci\u00f3n a la electr\u00f3nica",
                        p: "crk_ele_1300",
                        c: "lectura",
                        pc: "-rob\u00f3tica-robot-electr\u00f3nica-LED-resistencia-protoboard-LED-interruptores-botones-bot\u00f3n-push button-potenci\u00f3metro-fotorresistencia-zumbador-buzzer\n",
                        o: "-\tConoce el contenido del bloque de electr\u00f3nica de CRK.\n",
                      },
                      {
                        i: "8832",
                        n: "1. Corriente el\u00e9ctrica",
                        p: "crk_ele_1301a",
                        c: "video",
                        pc: "-rob\u00f3tica-electr\u00f3nica-Aztek-corriente el\u00e9ctrica-el\u00e9ctrica-neutrones-protones-positiva-negativa-electrones-carga-silla-rinoceronte-carga-cadena-pr\u00e9stamos-desequilibra",
                        o: "-\tIdentifica las partes de un \u00e1tomo.\n-\tReconoce la importancia de los electrones.\n-\tConoce c\u00f3mo se genera la corriente el\u00e9ctrica.\t\n\n",
                      },
                      {
                        i: "8882",
                        n: "2. Introducci\u00f3n a la electr\u00f3nica ",
                        p: "crk_ele_1301b",
                        c: "video",
                        pc: "-rob\u00f3tica-electr\u00f3nica-Aztek-electr\u00f3nica-aislante-conductor-semiconductor-corriente-el\u00e9ctrica-alterna-continua-movimiento-electrones-carga-positiva-negativa-bater\u00edas-tableta-celular-aud\u00edfonos-pila-tostador-lavadora-puerta el\u00e9ctrica-aparatos dom\u00e9sticos-silicio-arena-playa-metal-pl\u00e1stico-madera-directa",
                        o: "-\tConoce el objeto de estudio de la electr\u00f3nica.\n-\tExplica la diferencia entre la corriente directa y la alterna.\n-\tReconoce los materiales que son conductores, semiconductores y aislantes de la corriente el\u00e9ctrica.\n",
                      },
                      {
                        i: "8883",
                        n: "3. Diagrama pict\u00f3rico  y esquem\u00e1tico",
                        p: "crk_ele_1301c",
                        c: "video",
                        pc: "-rob\u00f3tica-electr\u00f3nica-Aztek-electr\u00f3nica-diagrama-pict\u00f3rico-esquem\u00e1tico-cable-dibujar-simbolog\u00eda-l\u00e1mpara-s\u00edmbolo-elementos-circuito el\u00e9ctrico-esquema-dibujo",
                        o: "-\tDiferencia un diagrama pict\u00f3rico de un esquem\u00e1tico.",
                      },
                    ],
                  },
                  {
                    id: 96358,
                    n: "Protoboard",
                    position: 2,
                    tipo: "leccion",
                    apps: [
                      {
                        i: "8833",
                        n: "1. La protoboard",
                        p: "crk_ele_1302a",
                        c: "video",
                        pc: "-rob\u00f3tica-electr\u00f3nica-protoboard-circuitos-cables-positivo-negativo-orificios-placa-prueba-perforaciones-experimentos-componentes-conductor-electricidad-tiras-met\u00e1licas",
                        o: "-\tIdentifica una protoboard.\n-\tMenciona la funci\u00f3n de una protoboard.\n-\tConoce los beneficios de una protoboard.\n-\tConoce la estructura de una protoboard y c\u00f3mo usarla.\n\n",
                      },
                    ],
                  },
                  {
                    id: 96359,
                    n: "Resistencia",
                    position: 3,
                    tipo: "leccion",
                    apps: [
                      {
                        i: "8834",
                        n: "1. La resistencia",
                        p: "crk_ele_1303a",
                        c: "video",
                        pc: "-rob\u00f3tica-electr\u00f3nica-corriente-circuitos-cables-resistencia-c\u00f3digo-colores-ohms-intensidad-bandas-naranja-roja-amarillo-tolerancia-plata-conducir-electricidad-electrones-cer\u00e1mica-carbono-espirales",
                        o: "-\tIdentifica a una resistencia.\n-\tConoce el funcionamiento de una resistencia.\n-\tConoce el significado del c\u00f3digo de colores de una resistencia.\n-\tConoce los beneficios que aporta una resistencia.\n",
                      },
                      {
                        i: "8588",
                        n: "2. Pinta tu resistencia",
                        p: "crk_ele_1303b",
                        c: "aplicacion",
                        pc: "-rob\u00f3tica-resistencia-ohms-rojo-negro-caf\u00e9-naranca-amarillo-verde-azul-violeta-gris-blanco-tolerancia",
                        o: "-\tReconoce el significado del color de las bandas en una resistencia.\n-\tCalcula el valor de una resistencia y su tolerancia.\n-\tReconoce la unidad de medida de la resistencia.\n",
                      },
                    ],
                  },
                  {
                    id: 96360,
                    n: "LED",
                    position: 4,
                    tipo: "leccion",
                    apps: [
                      {
                        i: "8835",
                        n: "1. Diodo emisor de luz",
                        p: "crk_ele_1304a",
                        c: "video",
                        pc: "-rob\u00f3tica-electr\u00f3nica-corriente-circuitos-cables-diodo-emisor-luz-LED-colores-destello-RGB-electrones-infrarrojo-luz-encendido-apagado-rojo-f\u00f3sforo-azul-amarillo",
                        o: "-\tIdentifica a un LED.\n-\tConoce la evoluci\u00f3n de los LEDs.\n-\tMenciona los beneficios de un LED relacionados con el  medio ambiente.\n",
                      },
                      {
                        i: "8192",
                        n: "2. Prende tu LED",
                        p: "crk_ele_1304b1",
                        c: "simuladorcrk",
                        pc: "-rob\u00f3tica-LED-protoboard-resistencia-prender-positivo-negativo-fuente-poder-polaridad",
                        o: "-\t Conecta y prende un LED. \n-\tExplica para qu\u00e9 se requiere una Resistencia al conectar un LED.\n",
                      },
                      {
                        i: "8283",
                        n: "3. Conecta tus LEDs en paralelo y en serie",
                        p: "crk_ele_1304b2",
                        c: "simuladorcrk",
                        pc: "-rob\u00f3tica-LED-protoboard-resistencia-prender-positivo-negativo-fuente-poder-polaridad-paralelo-serie-circuito-energ\u00eda",
                        o: "-\t Construye un circuito de LEDs conectado en paralelo.\n-\tConstruye un circuito de LEDs conectado en serie.\n-\tEnlista las diferencias entre un circuito conectado en paralelo y uno en serie. \n",
                      },
                    ],
                  },
                  {
                    id: 96361,
                    n: "Interruptores y botones",
                    position: 5,
                    tipo: "leccion",
                    apps: [
                      {
                        i: "8836",
                        n: "1. Interruptores y botones",
                        p: "crk_ele_1305a",
                        c: "video",
                        pc: "-rob\u00f3tica-electr\u00f3nica-corriente-circuitos-cables-interruptores-botones-energ\u00eda-interruptor-bot\u00f3n-corriente-el\u00e9ctrica-entrada-salida-apagador-luz-resorte-placas-celular-mensaje-voz-l\u00e1mpara",
                        o: "-\tConoce el funcionamiento de un  interruptor y un bot\u00f3n.\n-\tDiferencia entre un bot\u00f3n y un interruptor.\n-\tEnlista los usos de los interruptores y botones.\n",
                      },
                      {
                        i: "8284",
                        n: "2. Prende un LED con un push button y luego con un switch deslizable",
                        p: "crk_ele_1305b1",
                        c: "simuladorcrk",
                        pc: "-rob\u00f3tica-LED-protoboard-resistencia-fuente-poder-switch-push-button-bot\u00f3n-interruptor-positivo-negativo-circuito",
                        o: "-  Explica la diferencia entre un Push button (Bot\u00f3n) y un Switch deslizable de un Dip switch. ",
                      },
                      {
                        i: "8333",
                        n: "3. Interruptores de escalera",
                        p: "crk_ele_1305b2",
                        c: "simuladorcrk",
                        pc: "-rob\u00f3tica-LED-protoboard-resistencia-fuente-poder-switch-push-button-bot\u00f3n-interruptor-positivo-negativo-circuito",
                        o: "-\t Describe el funcionamiento de un Potenci\u00f3metro.",
                      },
                    ],
                  },
                  {
                    id: 96362,
                    n: "Potenci\u00f3metro y fotorresistencia",
                    position: 6,
                    tipo: "leccion",
                    apps: [
                      {
                        i: "8837",
                        n: "1. Potenci\u00f3metros y fotorresistencias",
                        p: "crk_ele_1306a",
                        c: "video",
                        pc: "-corriente-el\u00e9ctrica-intensidad-regular-flujo-electrones-resistencia-potenci\u00f3metro-volumen-m\u00fasica-luz",
                        o: "- Conoce la forma de regular la intensidad de la corriente el\u00e9ctrica.\n- Reconoce la importancia de un potenci\u00f3metro.\n- Enlista ejemplos de los usos de un potenci\u00f3metro.",
                      },
                      {
                        i: "8338",
                        n: "2. Incremento en una resistencia",
                        p: "crk_ele_1306b1",
                        c: "simuladorcrk",
                        pc: "-rob\u00f3tica-LED-protoboard-resistencia-fuente-poder-switch-circuito-incrementar",
                        o: "-\tIncrementa la resistencia en un circuito. \n-\tDescribe el efecto de incrementar la resistencia en un circuito.\n\n",
                      },
                      {
                        i: "8394",
                        n: "3. Uso del potenci\u00f3metro",
                        p: "crk_ele_1306b2",
                        c: "simuladorcrk",
                        pc: "-rob\u00f3tica-LED-protoboard-resistencias-potenci\u00f3metro-fuente-poder-serie",
                        o: "- Descubre y describe el funcionamiento del Potenci\u00f3metro.",
                      },
                      {
                        i: "8395",
                        n: "4. La fotorresistencia",
                        p: "crk_ele_1306b3",
                        c: "simuladorcrk",
                        pc: "-rob\u00f3tica-LED-protoboard-resistencias-fotorresistencia-fuente-poder-l\u00e1mpara",
                        o: "-\tDescribe el uso de la Fotorresistencia.",
                      },
                      {
                        i: "8427",
                        n: "5. El LED multicolor, RGB",
                        p: "crk_ele_1306b4",
                        c: "simuladorcrk",
                        pc: "-rob\u00f3tica-LED-RGB-protoboard-resistencias-potenci\u00f3metro-fuente-poder-serie-azul-rojo-verde-red-green-blue",
                        o: "-\tConoce el LED RGB.\n-\tExperimenta la variaci\u00f3n de sus colores utilizando potenci\u00f3metros.\n",
                      },
                    ],
                  },
                  {
                    id: 96363,
                    n: "Zumbador o buzzer",
                    position: 7,
                    tipo: "leccion",
                    apps: [
                      {
                        i: "8838",
                        n: "1. Zumbador o buzzer",
                        p: "crk_ele_1307a",
                        c: "video",
                        pc: "-rob\u00f3tica-zumbador-buzzer-zumbido-sonido-placa-cer\u00e1mica-met\u00e1lica-oscilador-bot\u00f3n-alarma-electrodom\u00e9sticos-bot\u00f3n de p\u00e1nico-alarma",
                        o: "- Conoce el funcionamiento de un zumbador o buzzer.\n- Enlista los usos cotidianos de un zumbador o buzzer.",
                      },
                      {
                        i: "8462",
                        n: "2. El bot\u00f3n de p\u00e1nico",
                        p: "crk_ele_1307b1",
                        c: "simuladorcrk",
                        pc: "-rob\u00f3tica-LED-zumbador-push button-bot\u00f3n-resistencia-bot\u00f3n-terminal-positiva-negativa-p\u00e1nico",
                        o: "- Construye un bot\u00f3n de p\u00e1nico.",
                      },
                      {
                        i: "8463",
                        n: "3. La alarma y el camale\u00f3n",
                        p: "crk_ele_1307b2",
                        c: "simuladorcrk",
                        pc: "-rob\u00f3tica-LED-zumbador-RGB camale\u00f3n-resistencia-terminal-positiva-negativa-camale\u00f3n-alarma",
                        o: "-\tConoce el LED RGB camale\u00f3n.\n-\tEncuentra las diferencias entre un LED RGB y un LED RGB camale\u00f3n.\n-\tConstruye una alarma e integra un LED RGB camale\u00f3n en ella.\n",
                      },
                    ],
                  },
                  {
                    id: 96491,
                    n: "Evaluaci\u00f3n",
                    position: 8,
                    tipo: "leccion",
                    apps: [
                      {
                        i: "8941",
                        n: "\u00bfQu\u00e9 tanto sabes de electr\u00f3nica b\u00e1sica?",
                        p: "crk_ele_1309a",
                        c: "evaluacionC",
                        pc: "-evaluaci\u00f3n-rob\u00f3tica-electr\u00f3nica-diodo-led-resistencia-potenci\u00f3metro-fotorresistencia-buzzer-zumbador-neutr\u00f3n-prot\u00f3n-electr\u00f3n-materia-\u00e1tomo- carga-corriente el\u00e9ctrica-esquema-diagrama pict\u00f3rico-s\u00edmbolo-aislante- conductor-semiconductor-bot\u00f3n-interruptor-corriente directa-alterna-bater\u00eda-enchufe-cobre-madera-ohm",
                        o: "Describe qu\u00e9 es la corriente el\u00e9ctrica.\n- Identifica los principales componentes de electr\u00f3nica b\u00e1sica.\n- Reconoce los s\u00edmbolos universales de los componentes de la electr\u00f3nica base.\n",
                      },
                    ],
                  },
                ],
              },
              {
                id: 33718,
                n: "Programaci\u00f3n",
                position: 4,
                tipo: "bloque",
                lecciones: [
                  {
                    id: 95455,
                    n: "Pro. por bloques",
                    position: 1,
                    tipo: "leccion",
                    apps: [
                      {
                        i: "8419",
                        n: "3. Enciende tu LED",
                        p: "crk_pro_2203b",
                        c: "simuladorcrk",
                        pc: "-LED-electr\u00f3nica-rob\u00f3tica-programaci\u00f3n-simulaci\u00f3n-bloques-encender-arduino-shield-protoboard",
                        o: "- Utiliza un bloque de programaci\u00f3n para encender un LED.\n- Configura un bloque LED.\n",
                      },
                      {
                        i: "8420",
                        n: "4. \u00bfQu\u00e9 hacen un LED y un Retardo juntos?",
                        p: "crk_pro_2204b",
                        c: "simuladorcrk",
                        pc: "-LED-retardo-electr\u00f3nica-rob\u00f3tica-programaci\u00f3n-simulaci\u00f3n-bloques-encender-apagar-arduino-protoboard-shield",
                        o: "- Programa un LED para que se prenda y se apague por un tiempo determinado.",
                      },
                    ],
                  },
                ],
              },
            ],
            status: 0,
          },
        ],
      }
    ],
  },
};
